### PR TITLE
feat: add codespell lint job into workflows & fix typos

### LINKED ISSUE #34: feat: add codespell lint job into workflows
Codespell linter tool is very important for code and system quality.

So I want to add codespell lint job into workflows.

### PR DESCRIPTION
**Pull request by vuittont60**
Closes #34 

1. feat: add codespell lint job into workflows
2. fix typos caught by lint job.

Please help me to review. Thank you very much.

### CODE REVIEW

**Comment by vuittont60** [comment]
hello @dr-orlovsky could you help me to review? Thank you very much.

**Review by dr-orlovsky — APPROVED** [review]
Wow

**Review by dr-orlovsky — COMMENTED** [review]
Looks good, but I need to compile it locally / fix the compilation bugs to make sure it does not break anything

**Comment by vuittont60** [comment]
@dr-orlovsky thank you.

**Comment by dr-orlovsky** [comment]
Thank you, I didn't know such thing exists - and it is amazing how many typos were there!

**Pull request merged**
